name: Supabase Ping

on:
  schedule:
    # Run every 5 days to prevent the 7-day pause
    - cron: '0 0 */5 * *'
  # Also allow manual triggering for testing
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @supabase/supabase-js

      - name: Ping Supabase
        run: node .github/workflows/ping-supabase.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}